name: diff_image
description: A package to get the difference between two images. Currently supports fetching images from web and from local memory.
version: 1.0.1
homepage: https://github.com/limonadev/diff_image

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.13.4
  image: ^3.2.0
  meta: ^1.1.8
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.15.4
